pub const CAPSULE_HALF_HEIGHT: f32 = 0.6;
pub const CAPSULE_RADIUS: f32 = 0.4;

pub const CAPSULE_CENTER_TO_BOTTOM: f32 = CAPSULE_HALF_HEIGHT + CAPSULE_RADIUS;

pub const PLAYER_VISUAL_OFFSET_Y: f32 = -1.55;

pub const ENEMY_VISUAL_OFFSET_Y: f32 = -CAPSULE_CENTER_TO_BOTTOM;

pub const TNUA_FLOAT_HEIGHT: f32 = CAPSULE_CENTER_TO_BOTTOM + 0.03;
